/*
 * SPDX-FileCopyrightText: 2023-2024 The LineageOS Project
 * SPDX-License-Identifier: Apache-2.0
 */

package org.lineageos.generatebp

import org.gradle.api.Project
import org.gradle.kotlin.dsl.get
import org.lineageos.generatebp.ext.*
import org.lineageos.generatebp.models.Artifact
import org.lineageos.generatebp.models.License
import org.lineageos.generatebp.models.Module
import org.lineageos.generatebp.utils.ReuseUtils
import java.io.File

internal class GenerateBp(
    private val project: Project,
    private val targetSdk: Int,
    private val isAvailableInAOSP: (module: Module) -> Boolean,
    private val libsBase: File = File("${project.projectDir.absolutePath}/libs"),
) {
    init {
        // When running in CI, override current year with the one from the libs/Android.bp file
        if (System.getenv("CI") == "true") {
            ReuseUtils.readCurrentCopyrightYear("$libsBase/Android.bp")?.let {
                ReuseUtils.currentYear = it
            }
        }
    }

    private val configuration = project.configurations["releaseRuntimeClasspath"]
    private val resolvedConfiguration = configuration.resolvedConfiguration

    private val firstLevelDependencies = resolvedConfiguration.firstLevelModuleDependencies.filter {
        // kotlin-bom does not need to be added to dependencies
        it.moduleGroup != "org.jetbrains.kotlin" && it.moduleName != "kotlin-bom"
    }

    private val projectDependencies = firstLevelDependencies.map {
        Module.fromResolvedDependency(it, targetSdk)
    }

    private val allDependencies = firstLevelDependencies.asSequence().map {
        it.recursiveDependencies
    }.flatten().toSet().map {
        Module.fromResolvedDependency(it, targetSdk)
    }.toSortedSet()

    private val libsAndroidBpHeader = buildString {
        append("//\n")
        append(
            ReuseUtils.generateReuseCopyrightContent(
                License.APACHE_2_0,
                listOf("The LineageOS Project"),
                initialYear = ReuseUtils.readInitialCopyrightYear("$libsBase/Android.bp"),
                addNewlineBetweenCopyrightAndLicense = false,
                addEndingNewline = false
            ).prependIndent("// ")
        )
        append("\n")
        append("//\n")
        append("\n")
        append("// DO NOT EDIT THIS FILE MANUALLY\n")
    }

    private val mainAndroidBpHeader = buildString {
        append("//\n")
        append(
            ReuseUtils.generateReuseCopyrightContent(
                License.APACHE_2_0,
                listOf("The LineageOS Project"),
                initialYear = ReuseUtils.readInitialCopyrightYear("${project.projectDir.absolutePath}/Android.bp"),
                addNewlineBetweenCopyrightAndLicense = false,
                addEndingNewline = false
            ).prependIndent("// ")
        )
        append("\n")
        append("//\n")
        append("\n")
    }

    operator fun invoke() {
        // Delete old libs artifacts
        libsBase.deleteRecursively()

        // Update app/Android.bp
        File("${project.projectDir.absolutePath}/Android.bp").let { file ->
            val dependenciesString = buildString {
                append("\n")
                append(SHARED_LIBS_HEADER.indentWithSpaces(8))
                append("\n")
                append(
                    projectDependencies.map {
                        "\"${it.aospModuleName}\","
                    }.indentWithSpaces(8).joinToString("\n")
                )
                append("\n${spaces(4)}")
            }

            var isAndroid: Boolean

            val mainAndroidBpPlaceholder = buildString {
                if (project.plugins.hasPlugin("com.android.application")) {
                    append("android_app {\n")
                    isAndroid = true
                } else if (project.plugins.hasPlugin("com.android.library")) {
                    append("android_library {\n")
                    isAndroid = true
                } else {
                    append("java_library_static {\n")
                    isAndroid = false
                }
                append("    name: \"${project.rootProject.name}\",\n" )
                append("    certificate: \"platform\",\n")
                append("    system_ext_specific: true,\n")
                append("    sdk_version: \"34\",\n")
                append("\n")
                if (isAndroid == true) {
                    append("    resource_dirs: [\"src/main/res\"],\n")
                    append("\n")
                }
                append("    srcs: [\n")
                append("        \"src/main/java/**/*.kt\",\n")
                append("        \"src/main/java/**/*.java\",\n")
                append("    ],\n")
                append("\n")
                if (isAndroid == true) {
                   append("    manifest: \"src/main/AndroidManifest.xml\",\n")
                   append("\n")
                }
                append("    static_libs: [\n")
                append("        //PLACEHOLDER\n")
                append("    ],\n")
                append("\n")
                append("    kotlincflags: [\"-Xjvm-default=all\"],\n")
                append("}")
            }

            // Add autogenerated contents if file is empty
            if (file.length() == 0L) {
                file.writeText(mainAndroidBpHeader)
                file.appendText(mainAndroidBpPlaceholder)
            }

            file.writeText(
                file.readText().replace(
                    // Replace existing dependencies with newly generated ones
                    "static_libs: \\[.*?]".toRegex(RegexOption.DOT_MATCHES_ALL),
                    "static_libs: [%s]".format(dependenciesString)
                ).replace(
                    // Replace existing sdk_version with one from targetSdk
                    "sdk_version: \"\\d+\"".toRegex(),
                    "sdk_version: \"${targetSdk}\""
                )
            )
        }

        // Update app/libs
        allDependencies.forEach {
            // Skip modules that are available in AOSP
            if (isAvailableInAOSP(it)) {
                return@forEach
            }

            // Create dir
            libsBase.mkdirs()

            it.artifact?.let { artifact ->
                // Get file path
                val dirPath = "${libsBase}/${it.aospModulePath}"
                val filePath = "${dirPath}/${artifact.file.name}"

                // Copy artifact to app/libs
                artifact.file.copyTo(File(filePath))

                // Write license file
                artifact.writeCopyrightFileForFile(filePath)

                // Extract AndroidManifest.xml for AARs
                if (artifact.file.extension == "aar") {
                    project.copy {
                        from(project.zipTree(filePath).matching {
                            include("/AndroidManifest.xml")
                        }.singleFile)
                        into(dirPath)
                    }

                    // Write license file
                    artifact.writeCopyrightFileForFile("${dirPath}/AndroidManifest.xml")
                }
            }

            // Write Android.bp
            File("$libsBase/Android.bp").let { file ->
                // Add autogenerated header if file is empty
                if (file.length() == 0L) {
                    file.writeText(libsAndroidBpHeader)
                }

                it.artifact?.also { artifact ->
                    when (artifact.fileType) {
                        Artifact.FileType.AAR -> {
                            file.appendText(
                                """

                                android_library_import {
                                    name: "${it.aospModuleName}-nodeps",
                                    aars: ["${it.aospModulePath}/${artifact.file.name}"],
                                    sdk_version: "${artifact.targetSdkVersion}",
                                    min_sdk_version: "${artifact.minSdkVersion}",
                                    apex_available: [
                                        "//apex_available:platform",
                                        "//apex_available:anyapex",
                                    ],
                                    static_libs: [%s],${when (artifact.hasJNIs) {
                                            true -> """
                                    extract_jni: true,"""
                                            false -> ""
                                        }
                                    }
                                }
    
                                android_library {
                                    name: "${it.aospModuleName}",
                                    sdk_version: "${artifact.targetSdkVersion}",
                                    min_sdk_version: "${artifact.minSdkVersion}",
                                    apex_available: [
                                        "//apex_available:platform",
                                        "//apex_available:anyapex",
                                    ],
                                    manifest: "${it.aospModulePath}/AndroidManifest.xml",
                                    static_libs: [%s],
                                    java_version: "1.7",
                                }

                                """.trimIndent().format(
                                    it.formatDependencies(false),
                                    it.formatDependencies(true)
                                )
                            )
                        }

                        Artifact.FileType.JAR -> {
                            file.appendText(
                                """
    
                                java_import {
                                    name: "${it.aospModuleName}-nodeps",
                                    jars: ["${it.aospModulePath}/${artifact.file.name}"],
                                    sdk_version: "${artifact.targetSdkVersion}",
                                    min_sdk_version: "${artifact.minSdkVersion}",
                                    apex_available: [
                                        "//apex_available:platform",
                                        "//apex_available:anyapex",
                                    ],
                                }
    
                                java_library_static {
                                    name: "${it.aospModuleName}",
                                    sdk_version: "${artifact.targetSdkVersion}",
                                    min_sdk_version: "${artifact.minSdkVersion}",
                                    apex_available: [
                                        "//apex_available:platform",
                                        "//apex_available:anyapex",
                                    ],
                                    static_libs: [%s],
                                    java_version: "1.7",
                                }

                                """.trimIndent().format(
                                    it.formatDependencies(true)
                                )
                            )
                        }
                    }
                } ?: file.appendText(
                    """

                    java_library_static {
                        name: "${it.aospModuleName}",
                        sdk_version: "$targetSdk",
                        min_sdk_version: "${Artifact.DEFAULT_MIN_SDK_VERSION}",
                        apex_available: [
                            "//apex_available:platform",
                            "//apex_available:anyapex",
                        ],
                        static_libs: [%s],
                        java_version: "1.7",
                    }

                    """.trimIndent().format(
                        it.formatDependencies(false)
                    )
                )
            }
        }
    }

    private val Module.aospModuleName
        get() = if (isAvailableInAOSP(this)) {
            moduleNameAOSP("${group}:${name}")
        } else {
            "${project.rootProject.name}_${group}_${name}"
        }

    private fun Module.formatDependencies(addNoDependencies: Boolean): String {
        val aospDependencies = dependencies.asSequence().filter { dep ->
            when {
                dep.group == "org.jetbrains.kotlin" && dep.name == "kotlin-stdlib-common" -> false
                else -> true
            }
        }.distinct().map {
            it.aospModuleName
        }.sorted().toMutableList()

        if (addNoDependencies) {
            // Add -nodeps dependency for android_library/java_library_static
            aospDependencies.add(0, "${aospModuleName}-nodeps")
        }

        return aospDependencies.map {
            "\"${it}\","
        }.indentWithSpaces(8).joinToString("") {
            "\n$it"
        } + "\n${spaces(4)}"
    }

    companion object {
        private const val SHARED_LIBS_HEADER = "// DO NOT EDIT THIS SECTION MANUALLY"

        private fun moduleNameAOSP(moduleName: String) = when (moduleName) {
            "androidx.annotation:annotation-jvm" -> "androidx.annotation_annotation"
            "androidx.constraintlayout:constraintlayout" -> "androidx-constraintlayout_constraintlayout"
            "androidx.test.espresso:espresso-accessibility" -> "androidx.test.espresso.accessibility"
            "androidx.test.espresso:espresso-contrib" -> "androidx.test.espresso.contrib"
            "androidx.test.espresso:espresso-core" -> "androidx.test.espresso.core"
            "androidx.test.espresso:espresso-idling-resource" -> "androidx.test.espresso.idling-resource"
            "androidx.test.espresso:espresso-intents" -> "androidx.test.espresso.intents"
            "androidx.test.espresso:espresso-web" -> "androidx.test.espresso.web"
            "com.google.auto.value:auto-value-annotations" -> "auto_value_annotations"
            "com.google.errorprone:error_prone_annotations" -> "error_prone_annotations"
            "com.google.errorprone:error_prone_core" -> "error_prone_core"
            "com.google.guava:guava" -> "guava"
            "com.google.guava:listenablefuture" -> "guava"
            "org.jetbrains.kotlin:kotlin-stdlib" -> "kotlin-stdlib"
            "org.jetbrains.kotlin:kotlin-stdlib-jdk7" -> "kotlin-stdlib-jdk7"
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8" -> "kotlin-stdlib-jdk8"
            "org.jetbrains.kotlinx:kotlinx-coroutines-android" -> "kotlinx-coroutines-android"
            "org.jetbrains.kotlinx:kotlinx-coroutines-core" -> "kotlinx-coroutines-core"
            "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm" -> "kotlinx-coroutines-core-jvm"
            "org.jetbrains.kotlinx:kotlinx-coroutines-guava" -> "kotlinx_coroutines_guava"
            "org.jetbrains.kotlinx:kotlinx-coroutines-reactive" -> "kotlinx_coroutines_reactive"
            "org.jetbrains.kotlinx:kotlinx-coroutines-rx2" -> "kotlinx_coroutines_rx2"
            else -> moduleName.replace(":", "_")
        }

        private fun Artifact.writeCopyrightFileForFile(file: String) {
            reuseCopyrightFileContent.takeIf { it.isNotEmpty() }?.let {
                File("$file.license").writeText(it)
            }
        }
    }
}
